### 유저 생성
POST {{BASE_URL}}/user/create
Content-Type: application/json

{
    "name": "testUser",
    "email": "testPass",
    "password": "1234"
}

### 유저 로그인
POST {{BASE_URL}}/user/login
Content-Type: application/json

{
  "email": "testPass",
  "password": "1234"
}

> {% client.global.set("token", response.body.accessToken); %}

### 관리자 로그인
POST {{BASE_URL}}/user/login
Content-Type: application/json

{
  "email": "root",
  "password": "1234"
}

> {% client.global.set("token", response.body.accessToken); %}


### 유저정보
GET {{BASE_URL}}/admin/user/list
Content-Type: application/json
Authorization: Bearer {{token}}
