spring:
  application:
    name: BackEnd
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MARIADB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect

server:
  port: 8080

api-keystt:
  naver: ${NAVER_API_KEY}
  kakao: ${KAKAO_API_KEY}


