spring:
  application:
    name: BackEnd
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MARIADB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect

server:
  port: 8080

api-keystt:
  kakao: ${KAKAO_API_KEY}

jwt:
  secret: ${JWT_SECRET:your-secret-key-should-be-at-least-32-characters-long}
  token-validity-in-seconds: 86400  # 24시간
