server:
  port: 8080

spring:
  application:
    name: BackEnd
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MARIADB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect

# 토큰관련
secret:
  admin:
    admin-id : ${ADMIN_ID}
    admin-pass : ${ADMIN_PASS}
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXP}  # 24시간(밀리초)

