spring:
  application:
    name: BackEnd
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MARIADB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect

# 보안 환경 변수
SECRET_ENV: ${SECRET_ENV_VALUE:default-value}
server:
  port: 8080

# 토큰관련
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXP}  # 24시간(밀리초)

