### Variables
@BASE_URL = http://localhost:8080

### POST 회원생성
POST {{BASE_URL}}/user/create
Content-Type: application/json

{
    "name": "testUser",
    "email": "testPass",
    "password": "1234"
}

### YOUTUBE GET
POST {{BASE_URL}}/user/login
Content-Type: application/json

{
  "email": "sejong",
  "password": "tpwhd"
}